version: "3.8"

networks:
  taurus-network:
    driver: bridge

services:
  taurus-mongodb:
    image: mongo:latest
    container_name: taurus-mongodb
    hostname: taurus-mongodb
    networks:
      - taurus-network
    volumes:
      - ./.docker/taurus-mongodb/data:/data/db
    ports:
      - 27017:27017
    environment:
      - TZ=America/Sao_Paulo
    restart: on-failure

  taurus-api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    container_name: taurus-api
    hostname: taurus-api
    networks:
      - taurus-network
    volumes:
      - .:/app
    ports:
      - 3000:3000
    entrypoint: sh .docker/entrypoint.sh
    environment:
      - APP_DESCRIPTION='API for making integrations'
      - APP_PORT=3000
      - APP_TITLE='Taurus API'
      - APP_TOKEN=k86Pa6@4B$-$ul%@ghvf
      - APP_VERSION=0.0.1
      - NODE_ENV=DEV
      - TZ=America/Sao_Paulo
